export default {
  primaryColor: "#FF6065",
  borderColor: "#ecebec",
  errorColor: "#F9595A",
  labelColor: "#B5B5B5",
  dropdownProps: {
    contained: false,
    arrowContained: false,
    arrowIcon: "arrowDropdownMohIcon",
    arrowColor: "#B5B5B5",
  },
  textInputProps: {
    labelFontFamily: "roboto-bold",
    labelFontSize: 13,
    labelColor: "#464243",
    fontFamily: "roboto-medium",
    fontSize: 14,
    textColor: "#464243",
    placeholderTextColor: "#B5B5B5",
    inactiveTintColor: "#B5B5B5",
    requiredColor: "#F9595A",
    withShadow: false,
  },
  buttonProps: {
    primaryColor: "#FF6065",
    secondaryColor: "#fff",
    disabledColor: "#993A3D",
    borderRadius: 4,
    borderWidth: 1,
    fontFamily: "roboto-bold",
    fontSize: 14,
    textTransform: "uppercase",
  },
  borderRadius: 4,
  borderWidth: 1,
};
