export default {
  primaryColor: "#00B7FF",
  secondaryColor: "#349BCF",
  borderColor: "#349BCF",
  errorColor: "#A90D23",

  dropdownProps: {
    contained: false,
    arrowContained: true,
    arrowIcon: "arrowDropdownLocalIcon",
    arrowColor: "white",
  },
  textInputProps: {
    labelFontFamily: "roboto-bold",
    labelFontSize: 13,
    fontFamily: "roboto-regular",
    fontSize: 14,
    textColor: "#55595C",
    placeholderTextColor: "#B5B5B5",
    inactiveTintColor: "#B5B5B5",
    requiredColor: "#A90D23",
    withShadow: false,
  },
  buttonProps: {
    primaryColor: "#00B7FF",
    secondaryColor: "#fff",
    disabledColor: "#00B7FF",
    borderRadius: 4,
    borderWidth: 1,
    fontFamily: "roboto-bold",
    fontSize: 14,
    textTransform: "uppercase",
  },
  borderRadius: 4,
  borderWidth: 1,
};
