export default {
  primaryColor: "#00B7FF",
  secondaryColor: "#349BCF",
  activeTintColor: "#349BCF",
  inactiveTintColor: "#00B7FF",
  defaultBorderColor: "#349BCF",
  defaultColor: "#55595c",
  defaultPlaceHolderTextColor: "#909090",
  // borderColor: "#B4DCED",
  red: "#CB2D24",
  green: "#449D44",
  orange: "#F7A445",
  grey: "#909090",
  disabledColor: "#909090",
  svgIcon: "#55595c",
  errorColor: "#A90D23",
  imageOpacityColor: "#2E241E",

  dropdownProps: {
    contained: false,
    arrowContained: true,
    arrowIcon: "arrowDropdownIcon",
    arrowColor: "white",
  },
  textInputProps: {
    labelFontFamily: "space-mono",
    labelFontSize: 13,
    labelColor: "black",
    fontFamily: "space-mono",
    fontSize: 14,
    textColor: "#55595c",
    placeholderTextColor: "#B5B5B5",
    inactiveTintColor: "#B5B5B5",
    requiredColor: "#A90D23",
  },
  buttonProps: {
    primaryColor: "#00B7FF",
    secondaryColor: "#fff",
    disabledColor: "#00B7FF",
    borderRadius: 4,
    borderWidth: 1,
    fontFamily: "space-mono",
    fontSize: 14,
    textTransform: "uppercase",
  },
  borderRadius: 4,
  borderWidth: 1,
};
